name: "All the sdk specific jobs"

on:
  workflow_call:

jobs:
  pub-dev-dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          channel: stable
          cache: true
      - name: Prepare publish
        run: ./package_flutter.sh
      - name: Check podfile
        run: cat publishing/flutter/ios/flutter_olm.podspec
      - name: pub.dev publish dry run
        working-directory: publishing/flutter
        run: |
          flutter pub get
          flutter pub publish --dry-run
  
  build_js:
    runs-on: ubuntu-latest
    container: docker.io/emscripten/emsdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build JS and WASM
        run: |
          make js
          zip olm.zip javascript/olm.js javascript/olm.wasm javascript/olm_legacy.js
      - uses: actions/upload-artifact@v3
        with:
          name: olm.zip
          path: olm.zip
