name: Publish to pub.dev

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

# Publish using the reusable workflow from dart-lang.
# Slightly modified to run our prep script first.
jobs:
  
  build_js:
    runs-on: ubuntu-latest
    container: docker.io/emscripten/emsdk:latest
    steps:
      - uses: actions/checkout@v4
      - name: Build JS and WASM
        run: |
          make js
          zip olm.zip javascript/olm.js javascript/olm.wasm javascript/olm_legacy.js
      - uses: actions/upload-artifact@v4
        with:
          name: olm.zip
          path: olm.zip

  publish:
    needs: [build_js]
    name: Publish to pub.dev
    environment: pub.dev
    permissions:
      contents: read
      id-token: write # This is required for requesting the JWT
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v4
      # Setup Dart SDK with JWT token
      - uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa
        with:
          flutter-version: '3.13.8'
          channel: stable
          cache: true
      - name: Prepare publish
        run: ./package_flutter.sh
      # Minimal package setup and dry run checks.
      - name: Install dependencies
        run: flutter pub get
        working-directory: publishing/flutter
      # has the oidc bits
      - uses: dart-lang/setup-dart@a57a6c04cf7d4840e88432aad6281d1e125f0d46 
      - name: Dry run 
        run: dart pub publish --dry-run
        working-directory: publishing/flutter
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
        working-directory: publishing/flutter

  create_release:
    needs: [build_js]
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: olm.zip
          path: .
      - name: Create release
        run: |
          gh release create ${{ github.ref_name }}
          gh release upload ${{ github.ref_name }} olm.zip --clobber
